/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emissornotapromissoria;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fabriscio
 */
public class MainFrame extends javax.swing.JFrame {

    
    private String numeroExtenso;
    private int quantidadeParcelas;
    private Date dataVencimento;
    private String valorParcela;
    private String nomeDevedor;
    private String cpfDevedor;
    private String localEmissão;
    private Date diaEmissão;
    private String nomeBeneficiario;
    private String cpfBeneficiario;
    private String enderecoDevedor;
    private String valorPorExtenso;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEmissor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputNomeEmissor = new javax.swing.JTextField();
        inputCPFEmissor = new javax.swing.JTextField();
        panelBeneficiario = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        inputNomeBeneficiario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputCPFBeneficiario = new javax.swing.JTextField();
        panelInfoNota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputQuantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputDataPrimeiroVenc = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        inputValorExtenso = new javax.swing.JTextField();
        inputValorParcela = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelEmissor.setBorder(javax.swing.BorderFactory.createTitledBorder("Emissor"));

        jLabel5.setText("Nome do Emissor");

        jLabel6.setText("CPF do Emissor");

        javax.swing.GroupLayout panelEmissorLayout = new javax.swing.GroupLayout(panelEmissor);
        panelEmissor.setLayout(panelEmissorLayout);
        panelEmissorLayout.setHorizontalGroup(
            panelEmissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmissorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelEmissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputCPFEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNomeEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEmissorLayout.setVerticalGroup(
            panelEmissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmissorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputNomeEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmissorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputCPFEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelBeneficiario.setBorder(javax.swing.BorderFactory.createTitledBorder("Beneficiário"));

        jLabel7.setText("Nome do beneficiário");

        jLabel8.setText("CPF do beneficiário");

        javax.swing.GroupLayout panelBeneficiarioLayout = new javax.swing.GroupLayout(panelBeneficiario);
        panelBeneficiario.setLayout(panelBeneficiarioLayout);
        panelBeneficiarioLayout.setHorizontalGroup(
            panelBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBeneficiarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(panelBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputCPFBeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNomeBeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBeneficiarioLayout.setVerticalGroup(
            panelBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBeneficiarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputNomeBeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelBeneficiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputCPFBeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelInfoNota.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da nota"));

        jLabel1.setText("Valor das Parcelas");

        jLabel2.setText("Quantidade");

        jLabel3.setText("Primeiro Vencimento");

        inputDataPrimeiroVenc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        inputDataPrimeiroVenc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputDataPrimeiroVencKeyTyped(evt);
            }
        });

        jLabel4.setText("Valor por Extenso");

        inputValorParcela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputValorParcelaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelInfoNotaLayout = new javax.swing.GroupLayout(panelInfoNota);
        panelInfoNota.setLayout(panelInfoNotaLayout);
        panelInfoNotaLayout.setHorizontalGroup(
            panelInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoNotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputValorParcela, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(inputDataPrimeiroVenc))
                .addGroup(panelInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoNotaLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoNotaLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputValorExtenso, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInfoNotaLayout.setVerticalGroup(
            panelInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoNotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(inputDataPrimeiroVenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(inputValorExtenso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Emissor de Nota Promissória");

        jButton1.setBackground(new java.awt.Color(187, 240, 197));
        jButton1.setText("Gerar notas");

        jButton2.setBackground(new java.awt.Color(225, 178, 178));
        jButton2.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBeneficiario, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEmissor, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(panelInfoNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(panelInfoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBeneficiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputDataPrimeiroVencKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputDataPrimeiroVencKeyTyped
        
    }//GEN-LAST:event_inputDataPrimeiroVencKeyTyped

    private void inputValorParcelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputValorParcelaKeyReleased
        if(!inputValorParcela.getText().isEmpty()){
            String caracteres="0987654321";
            if(caracteres.contains(evt.getKeyChar()+"")){
                try {
                    boolean primeiroDigito = inputValorParcela.getText().length() == 1;
                    DecimalFormat decFormat = new DecimalFormat("#,###,##0.00");
                    decFormat.setParseBigDecimal(true);
                    BigDecimal valorBigDecimal = (BigDecimal) decFormat.parse(inputValorParcela.getText());
                    if(primeiroDigito){
                        valorBigDecimal = valorBigDecimal.divide(new BigDecimal(100.00));
                    } else {
                        valorBigDecimal = valorBigDecimal.multiply(new BigDecimal(10)).setScale(2, RoundingMode.HALF_UP);
                    }
                    String novoValor = decFormat.format(valorBigDecimal);
                    inputValorParcela.setText(novoValor);
                } catch (ParseException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                inputValorParcela.setText(inputValorParcela.getText().substring(0, inputValorParcela.getText().length()-1));
            }
        }
    }//GEN-LAST:event_inputValorParcelaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputCPFBeneficiario;
    private javax.swing.JTextField inputCPFEmissor;
    private javax.swing.JFormattedTextField inputDataPrimeiroVenc;
    private javax.swing.JTextField inputNomeBeneficiario;
    private javax.swing.JTextField inputNomeEmissor;
    private javax.swing.JTextField inputQuantidade;
    private javax.swing.JTextField inputValorExtenso;
    private javax.swing.JTextField inputValorParcela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelBeneficiario;
    private javax.swing.JPanel panelEmissor;
    private javax.swing.JPanel panelInfoNota;
    // End of variables declaration//GEN-END:variables
}
